# Sync Police Sandbox
## Import CSV files
CSV files from the __backend__, __Odoo__ and __planday__ can been exported manually. Let's see if we can export them automatically.

In [6]:
from pandas import read_csv
from os.path import join

csv_dir = '/Users/loicjounot/Code/internal-tools/sync_police/sandbox/drivers/'

In [7]:
odoo_filepath = join(csv_dir, 'odoo.csv')
odoo_df = read_csv(odoo_filepath)
odoo_df

,External ID,Active,Planday username,Backend UUID,Job Position,Salary ID,Driver App username,Name,Fleet/Name
0,__export__.res_partner_2303,True,NaN,6f1596ed-cc2d-4f53-b2b1-405e830285b9,Driver,279198,aftabs,Aftab Shafqat,birmingham
1,__export__.res_partner_3010,True,NaN,86638e4b-8646-44f8-a4b7-ca1cb6d0d094,Valk Driver Leicester,284845,aaka,Aamir Karim,leicester
2,__export__.res_partner_1877,True,NaN,f14b717a-c873-4550-af43-61a590542502,Driver,274578,AaYa,Aamir Yaqoob,london_zone_20
3,__export__.res_partner_3749,True,NaN,NaN,Driver,NaN,Ajohnson,Aaron Johnson,manchester
4,__export__.res_partner_989,True,NaN,aa7d7e68-5b27-40b5-9e86-c5245fe8cc39,Driver,240035,apervaiz,Aasim Pervaiz,birmingham
5,__export__.res_partner_623,True,NaN,92a58abf-c431-41d1-a144-9724b8ad6e0b,Driver,227979,sabbas,"Abbas, Sam",nottingham
6,__export__.res_partner_3116,True,NaN,a42d1cf3-1c7a-4019-bf8d-217f4271065c,Driver,286568,azeboudj,Abdel Malek Zeboudj,london_zone_j
7,__export__.res_partner_1432,True,NaN,5e44a4b3-6abe-40ca-a08d-c15553fa7e88,Driver,268112,ahassan3,Abdihamid Hassan,NaN
8,__export__.res_partner_1143,True,NaN,5f922c71-9f5e-49b4-8af2-d121578bd833,Driver,259419,aahmed,Abdul Ahmed,birmingham
9,__export__.res_partner_1227,True,NaN,3c0036ff-5b3d-45fa-8400-f44de120f112,Driver,261550,abdulali,Abdul Aziz Ali,birmingham
10,__export__.res_partner_1712,True,NaN,981cc0d8-64a6-48bd-8069-894da2cb4f89,Driver,271980,abari,Abdul Bari,london_leyton_stratford
11,__export__.res_partner_1297,True,NaN,12762d6b-f7d4-49a5-89dd-c87c497f174e,Driver,264630,AKuddoos,Abdul Kuddoos,birmingham
12,__export__.res_partner_868,True,NaN,f3527488-d498-4a15-a86a-a54cd95dde88,Driver,250625,amukhtar,Abdul Mukhtar,birmingham
13,__export__.res_partner_3291,True,NaN,NaN,Driver,NaN,abmu,Abdul Mumum,manchester
14,__export__.res_partner_1498,True,NaN,NaN,Driver,NaN,aqkhan,Abdul Qadoos Khan,london_leyton_stratford
15,__export__.res_partner_2712,True,NaN,fcc60a64-364c-4b2a-9dd0-a4f3444d1ed6,Driver,281435,aqayum,Abdul Qayum,manchester
16,__export__.res_partner_2639,True,NaN,99e03930-8772-4b16-b80d-5f5e98bcd227,Valk Driver Leicester,280791,asattar,Abdul Sattar,leicester
17,__export__.res_partner_2848,True,NaN,b1153c3c-6c63-4cfd-92ec-373254a603e9,Driver,283192,ayasar,Abdul Yasar,manchester
18,__export__.res_partner_3201,True,NaN,NaN,Driver,NaN,rabdul,"Abdul, Rashid",derby
19,__export__.res_partner_1299,True,NaN,d4dc0e19-a2ec-4826-830b-d422e751a686,Driver,264636,AbSaleh,Abdulgafar Saleh,birmingham
20,__export__.res_partner_1416,True,NaN,NaN,Driver,NaN,aalnamer,Abdullah Alnamer,NaN
21,__export__.res_partner_1229,True,NaN,91bc01ed-9f52-44f7-adc4-71df445c60c4,Driver,261555,abdullahk,Abdullah Khan,birmingham
22,__export__.res_partner_3179,True,NaN,d4dc0e19-a2ec-4826-830b-d422e751a686,Driver,264636,absaleh,Abdulmalik Saleh,birmingham
23,__export__.res_partner_634,True,NaN,e7a071a0-130e-4248-8e88-c6c62c1c14c0,Driver,209395,wabdulrasheed,"Abdulrasheed, Waheed",nottingham
24,__export__.res_partner_1381,True,NaN,c44f7fd4-8bad-467e-8246-2273db8edf29,Driver,267481,aharvey,Abi Harvey,basildon
25,__export__.res_partner_2906,True,NaN,NaN,Driver,NaN,habid,"Abid, Hussain",derby
26,__export__.res_partner_616,True,NaN,4e17b81d-6633-456d-a5a7-e3b13eddaddf,Driver,197673,nabiolasalam,"Abiola Salam, Nurein",nottingham
27,__export__.res_partner_3362,True,NaN,NaN,NaN,NaN,adjoudi,Abouelkacem Djoudi,london_zone_b
28,__export__.res_partner_3453,True,NaN,NaN,driver,NaN,acmahmood,Aclack Mahmood,leeds
29,__export__.res_partner_2341,True,NaN,NaN,NaN,NaN,NaN,Adam Frynas,warszawa
...,...,...,...,...,...,...,...,...,...
874,__export__.res_partner_1713,True,NaN,d3c62c06-d648-4cbc-8b4a-41b302b3b01a,Driver,271299,wassiss,Wisley Cesar Assiss,NaN
875,__export__.res_partner_1192,True,NaN,285b5dcd-fb29-42f8-85f3-06c1c4ffb59c,Driver,261427,JWisniewski,"Wisniewski, Jakub",nottingham
876,__export__.res_partner_1652,True,NaN,NaN,Driver,NaN,awlodarczyk,"Wlodarczyk, Artur",NaN
877,__export__.res_partner_2186,True,NaN,3b643480-342f-4ad4-8c8d-e4772b470fa9,Driver,277912,yahchen,Yahya Chentouf,london_zone_a
878,__export__.res_partner_1411,True,NaN,b4c5ace4-12e1-4098-a0fe-300b8ba25e95,Driver,268095,ymohammed,Yahya Mohammed,NaN
879,__export__.res_partner_3258,True,NaN,e355ebfd-f3c5-425e-82a0-cd88dc8bd8f8,Driver,286791,yasali,Yasin Ali,birmingham
880,__export__.res_partner_1753,True,NaN,6ed2427d-2be8-4b37-9e5d-6cd1968def9a,Driver,272283,YMehmood,Yasir Mehmood,london_zone_g
881,__export__.res_partner_3016,True,NaN,1e7d3a9c-ac83-4e99-9fdd-530f035acd78,Driver,284974,ysiddi,Yasir Siddique,manchester
882,__export__.res_partner_1653,True,NaN,NaN,Driver,NaN,gyordanov,"Yordanov, Georgi",NaN
883,__export__.res_partner_3228,True,NaN,NaN,Driver,NaN,youalg,Yousef Alghergani,manchester
884,__export__.res_partner_2049,True,NaN,NaN,NaN,NaN,zrisva,Zafer Risvanoglu,berlin
885,__export__.res_partner_792,True,NaN,NaN,Driver,NaN,zhussain,Zafran Hussain,birmingham
886,__export__.res_partner_1265,True,NaN,d7cc126c-f6db-43de-bb64-73eeec675373,Driver,263447,zahussain,Zaid Hussain,basildon
887,__export__.res_partner_2659,True,NaN,7fb7d0cf-3924-4ce8-a98c-0272c840d474,NaN,283943,zmardiny,Zaid Mardiny,liverpool
888,__export__.res_partner_1703,True,NaN,a7978456-1c03-4e3a-8002-4074e1e92ac9,Driver,271014,zmujaba,Zain Mujtaba,london_zone_g
889,__export__.res_partner_1952,True,NaN,NaN,NaN,NaN,zakmah,Zak Mahmood Coventry,coventry
890,__export__.res_partner_3298,True,NaN,NaN,Driver,NaN,zlatif,Zakaria Latif,london_zone_f
891,__export__.res_partner_3135,True,NaN,NaN,Valk Driver,NaN,znaim,Zakaria Naim,northampton
892,__export__.res_partner_275,True,NaN,NaN,Driver,NaN,zmahmood,Zaki Mahmood,coventry
893,__export__.res_partner_1793,True,NaN,NaN,Driver,NaN,zshahid,"Zaman, Shahid",NaN
894,__export__.res_partner_3279,True,NaN,NaN,Driver,NaN,zezu,"Zeb, Zuhaib",london_zone_20
895,__export__.res_partner_1889,True,NaN,533db974-8865-43b2-ba08-e1e3a96d9c81,Driver,274586,zchadd,Zeeshan Chaddhar,london_leyton_stratford
896,__export__.res_partner_969,True,NaN,87020c74-b49a-48f2-b6a5-dc8e2d8cddfb,Driver,253779,ztoor,Zeeshan Toor,NaN
897,__export__.res_partner_2088,True,NaN,NaN,Driver,NaN,zack,Zein Ackrem,london_zone_a
898,__export__.res_partner_2096,True,NaN,d6cd83c9-382b-465f-bdd7-009743b16aaf,Driver,276854,ksaidul,karim Saidul,coventry
899,__export__.res_partner_3265,True,NaN,NaN,Driver,NaN,elineny,no one,london_zone_20
900,__export__.res_partner_3170,True,NaN,NaN,NaN,NaN,NaN,test 22,berlin
901,__export__.res_partner_1811,True,NaN,NaN,NaN,NaN,NaN,test driver,manchester
902,__export__.res_partner_2691,True,NaN,NaN,NaN,NaN,odinm,Özkan Dinmezkalp,berlin
903,__export__.res_partner_2350,True,NaN,NaN,NaN,NaN,NaN,Łukasz Rajchman,warszawa

In [37]:
planday_filepath = join(csv_dir, 'planday.csv')
planday_df = read_csv(planday_filepath, sep=';', header=None)
planday_df

,0,1,2,3,4,5,6
0,﻿__test driver,360,_testdriver360,288542,NaN,NaN,NaN
1,__test driver 999,__test,___test3333,280585,NaN,NaN,NaN
2,__test1111,11,_test011,276535,NaN,NaN,NaN
3,_testdriver77,.,_testdriver77,274861,NaN,NaN,NaN
4,1,m,ahabibani,280916,NaN,NaN,NaN
5,Abdallah,Sina,abdallahsina,259090,Nottingham,NaN,NaN
6,Abdel Malek,Zeboudji,AZeboudji,286568,NaN,NaN,NaN
7,Abdelrazig,Sanousi,asanousi1,286661,Birmingham,NaN,NaN
8,Abdihamid,Hassan,abdihamid,268112,Birmingham,NaN,NaN
9,Abdul,Kuddoos,abdul.kuddoos,264630,birmingham,NaN,NaN
10,Abdul,Ahmed,abdul.ahmed,259419,NaN,NaN,NaN
11,Abdul,Mukhtar,abdul.mukhtar,250625,NaN,NaN,NaN
12,Abdul,Sattar,asattar,280791,Leicester,NaN,NaN
13,Abdul,Qayum,qayum,281435,MAnchester,NaN,NaN
14,Abdul,Armani,aarmani,277917,Birmingham,NaN,NaN
15,Abdul,Bari,ABari,271980,London,NaN,NaN
16,abdul,Mohamed,amohamed,286667,Birmingham,NaN,NaN
17,Abdul,Yasar,yasar,283192,Manchester,NaN,NaN
18,Abdul,Latif,alatif,286193,Birmingham,NaN,NaN
19,Abdul,Munim,amunim,288271,Manchester,NaN,NaN
20,Abdul Aziz,Ali,abdulaziz.ali,261550,Birmingham,NaN,NaN
21,Abdul Qadoos,Khan,AKhan,268755,London,NaN,NaN
22,Abdulgafar,Saleh,abdulgafar.saleh,264636,Birmingham,NaN,NaN
23,Abdulhamid,Ansi,aansi,286453,Birmingham,NaN,NaN
24,Abdullah,Al-Khazzan,abdullah2,286257,Birmingham,NaN,NaN
25,Abdullah,Khan,abdullah.khan,261555,Birmingham,NaN,NaN
26,Abdullah,Aziz,abdullah,258342,Nottingham,NaN,NaN
27,Abdulmalik,Saleh,asaleh2,286208,Birmingham,NaN,NaN
28,Abdulsalam,Ahmed,abdulsalamahmed,285045,Nottingham,NaN,NaN
29,Abdurahman,Mahmud,abdurahman,273693,Nottingham,NaN,NaN
...,...,...,...,...,...,...,...
761,Yahya,Chentouf,YChentouf,277912,London,NaN,NaN
762,yasin,ali,yali,286791,NaN,NaN,NaN
763,Yasir,Siddique,yasirs,284974,Manchester,NaN,NaN
764,Yasir,Mehmood,YMehmood,272283,London,NaN,NaN
765,Yousef,Alghergrani,yousefal,283506,Manchester,NaN,NaN
766,Youssef,El-idrissi,yelidrissi,276828,London,NaN,NaN
767,Yusef,Al Mubarak,yalmubarak,288223,London,NaN,NaN
768,Zafran,Hussain,zafran.hussain,247301,NaN,NaN,NaN
769,Zahier,Pasha,zahierpasha,275968,Nottingham,NaN,NaN
770,Zaid,Hussain,Zhussain,263447,Basildon,NaN,NaN
771,Zaid,Mardiny,zmardiny,283943,Liverpool,NaN,NaN
772,Zain,Hussain,zainhussain,273276,Nottingham,NaN,NaN
773,Zain,Mujaba,ZM,271014,Hayes,NaN,NaN
774,Zain Ul,Abddeen,zabddeen,279061,London,NaN,NaN
775,Zakaria,Latif,ZLatif,289967,London,NaN,NaN
776,Zakariya,haji,zhaji,286244,Birmingham,NaN,NaN
777,Zaki,Mahmood - COV,zaki.mahmood,236278,NaN,NaN,NaN
778,Zayn,Mahmood,zaynmahmood,280964,Nottingham,NaN,NaN
779,Zeenat,Begum,zeenatbegum,254589,Nottingham,NaN,NaN
780,Zeeshan,Chaddhar,zeechaddhar,274586,London,NaN,NaN
781,Zegham,Naveed,zeghamnaveed,259077,Nottingham,NaN,NaN
782,Zita,Balogh-Auer,zitabalogh,269658,NaN,NaN,NaN
783,Zubair,Ahmed,zubairahmed,285047,Nottingham,NaN,NaN
784,Zuhabib,Zeb,zzeb,287448,London,NaN,NaN
785,Aamir,Karim,akarim,284845,Leicester,NaN,NaN
786,Aamir,Yaqoob,aayaqoob,274578,London,NaN,NaN
787,Aaron,Pickering,a.pickering,275502,NaN,NaN,NaN
788,Aaron,Pickering,aaronpickering,275320,NaN,NaN,NaN
789,Aaron,Johnson,ajohnson,290032,Manchester,NaN,NaN
790,Aasim,Pervaiz,aasim.pervaiz,240035,Birmingham,NaN,NaN

In [5]:
backend_filepath = join(csv_dir, 'backend.csv')
backend_df = read_csv(backend_filepath, sep=',', parse_dates=['created_at', 'deleted_at'])
backend_df.head()

NameError: name 'join' is not defined

It looks like the __planday__ file is missing column descriptors.

## Checking data synchronization
This is a "though experiment" implementing fake data. The goal is to synchronize the above three data tables: __planday__, the __backend__ and __odoo__ (which acts as the mapper between __planday__ and __odoo__). I try to encompass most of the different ways that data can be missing.

### Summary of the fake data
* driver __0__ has been entered everwhere and has no empty fields
* driver __1__ has been entered everywhere but has an __empty field in planday__
* driver __2__ has been entered everywhere but has an __empty field in the backend__
* driver __3__ has been entered everywhere but has an __empty field in odoo__
* driver __4__ has been mapped in odoo but __no matching ID can be found in the backend__
* driver __5__ has been mapped in odoo but __no matching ID can be found in planday__
* driver __4__ has been mapped in odoo but __no matching ID can be found in the backend__
* driver __5__ has been mapped in odoo but __no matching ID can be found in planday__
* driver __6__ has been entered in the backend and planday but __not in odoo__
* driver __7__ has been entered in the __backend only__
* driver __8__ has been entered in __planday only__
* driver __9__ has been entered in __odoo only__
* driver __10__ has been entered in odoo with a planday ID but without a backend ID
* driver __11__ has been entered in odoo but the planday

In [ ]:
from pandas import DataFrame

df_backend = DataFrame({
    'id_backend': ['b0', 'b1', 'b2', 'b3', 'b5', 'b6', 'b7'], 
    'info_backend': ['toast', 'sausage', '<BACKEND>', 'beans', 'eggs', 'bacon', 'coffee']
})

df_planday = DataFrame({
    'id_planday': ['p0', 'p1', 'p2', 'p3', 'p4', 'p6', 'p8'], 
    'info_planday': ['star', '<PLANDAY>', 'wars', 'darth', 'vador', 'jedi', 'leia']
})

df_odoo = DataFrame({
    'id_odoo': ['o0', 'o1', 'o2', 'o3', 'o4', 'o5', 'o9'],
    'id_backend_in_odoo': ['b0', 'b1', 'b2', 'b3', '<ROSETTA>', 'b5', '<BACKEND>'], 
    'id_planday_in_odoo': ['p0', 'p1', 'p2', 'p3', 'p4', '<ROSETTA>', '<PLANDAY>'],
    'info_odoo': ['uk', 'usa', 'france', '<ODOO>', 'china', 'iceland', 'Egypt']
})

## Creating better fake data
The above is difficult to get consistent to I rationalised the whole thing and put it in one single table

In [ ]:
from pandas import DataFrame, read_sql_table
from dataset import connect
from sqlalchemy import create_engine

engine = create_engine('sqlite:///../../tests/assets/sync_police_test_cases.sqlite')
db = connect ('sqlite:///../../tests/assets/sync_police_test_cases.sqlite')

In [ ]:
db.load_table('test_cases_v1')

In [ ]:
tests_df = read_sql_table('test_cases_v1', engine)
tests_df

In [ ]:
from numpy import nan

df_backend = tests_df[['id_backend', 'info_backend', 'description']].replace('', nan)
df_backend.dropna(thresh=2, inplace=True)

### Backend table

In [ ]:
df_backend

## Planday table

In [ ]:
df_planday = tests_df[['id_planday', 'info_planday', 'description']].replace('', nan)
df_planday.dropna(thresh=2, inplace=True)
df_planday

## Odoo table

In [ ]:
df_odoo = tests_df[['id_odoo', 'info_odoo', 'id_planday_in_odoo', 'id_backend_in_odoo', 'description']].replace('', nan)
df_odoo.dropna(thresh=4, inplace=True)
df_odoo

In [ ]:
from pandas import merge

## Join Odoo with the backend
### Outer join on the odoo and backend tables.

In [ ]:
from numpy import nan

df_backend_with_odoo = merge(
    left=df_backend, 
    right=df_odoo, 
    left_on='id_backend', 
    right_on='id_backend_in_odoo', 
    how='outer'
).fillna('')

df_backend_with_odoo['description'] = df_backend_with_odoo['description_x'] + ' | ' + df_backend_with_odoo['description_y'] 
#df_backend_with_odoo['description'] = df_backend_with_odoo['description'].map(lambda x: x.split(' |')[0])
df_backend_with_odoo.replace('', nan)
del df_backend_with_odoo['description_x']
del df_backend_with_odoo['description_y']
df_backend_with_odoo

### Outer join on the odoo and planday tables

In [ ]:
df_planday_with_odoo = merge(
    left=df_planday, 
    right=df_odoo, 
    left_on='id_planday', 
    right_on='id_planday_in_odoo', 
    how='outer'
).fillna('')
df_planday_with_odoo
df_planday_with_odoo['description'] = df_planday_with_odoo['description_x'] + ' ' + df_planday_with_odoo['description_y'] 
df_planday_with_odoo.replace('', nan)
del df_planday_with_odoo['description_x']
del df_planday_with_odoo['description_y']
df_planday_with_odoo

### Inner join on the two intermediate tables
__Note__: the nature of the join is irrelevant. This could also be an outer, left or right join.

In [ ]:
df = merge(
    left=df_backend_with_odoo, 
    right=df_planday_with_odoo, 
    left_on='id_odoo', 
    right_on='id_odoo',
    suffixes=('_from_backend_join', '_from_planday_join'),
    how='inner'
)
df

### Delete redundant columns

In [ ]:
new_df = df
del new_df['id_planday_in_odoo_from_backend_join']
del new_df['id_backend_in_odoo_from_planday_join']
del new_df['info_odoo_from_backend_join']
del new_df['description_from_backend_join']
new_df

### Rename columns for clarity

In [ ]:
new_df.rename(columns = {'id_backend_in_odoo_from_backend_join':'id_backend_in_odoo'}, inplace = True)
new_df.rename(columns = {'id_planday_in_odoo_from_planday_join':'id_planday_in_odoo'}, inplace = True)
new_df.rename(columns = {'info_odoo_from_planday_join':'info_odoo'}, inplace = True)
new_df.rename(columns = {'description_from_planday_join':'description'}, inplace = True)
new_df

### Re-order the columns and rows

In [ ]:
ordered_columns = [
    'id_odoo',
    'info_odoo',
    'id_backend_in_odoo',
    'id_planday_in_odoo',
    'id_backend',
    'info_backend',
    'id_planday',
    'info_planday',
    'description'
]
new_df.reindex_axis(ordered_columns, axis=1).sort_values(by=['id_odoo', 'id_backend', 'id_planday'])

## Store the test cases inside a small database
Use python's [__dataset__](http://dataset.readthedocs.org/en/latest/) library to store test cases inside an sqlite database. This is more or less an excuse to try out this nigtfy little package. It also has two advantages:
* Multiple test cases can be stored inside one (sqlite) file
* Tests cases can be edited visually from your favorite database GUI (e.g. PyCharm)

In [4]:
from pandas import read_csv
from dataset import connect

In [5]:
db = connect ('sqlite:///../../tests/assets/test_db.sqlite')

In [6]:
test_cases_df = read_csv('../../tests/assets/sync_police_test_cases.csv', sep=';', index_col='Index')
test_cases_df.fillna('', inplace=True)
test_cases_df

OSError: File b'../../tests/assets/sync_police_test_cases.csv' does not exist

In [ ]:
test_cases_dict = test_cases_df.to_dict(orient='records')
test_cases_dict

In [ ]:
test_cases_table = db['junk']

In [ ]:
test_cases_table.insert_many(test_cases_dict)

## Test the YAML config file structure

In [ ]:
from yaml import load, load_all
from pprint import pprint

with open('/Users/loicjounot/Code/internal-tools/integration/configuration.yaml') as f:
    text = f.read()
    configs = load_all(text)
    
for config in configs:
    pprint(config)

### A simplified approach to merging tables
The above solution doesn't work. Let's try to implement our own merging algorithm. The basic insight is that the test case table we start with __is__ actually the solution we're looking for. Which means that we need to construct a table where at least on of the keys (__planday__, __backend__ or __odoo__) is present on each row. This however assumes __all three keys are unique__, otherwise things fall appart.

## Register class methods using decorators
This is essentially me learning meta-programming. I'm trying to implement an elegant solution to specify which columns of a dataframe to report and possibly rename the column at the same time. See [stackoverflow](http://stackoverflow.com/questions/5707589/calling-functions-by-array-index-in-python/5707605#5707605) for more information.

In [ ]:
def makeRegistrar():
    registry = {}
    def registrar(func):
        registry[func.__name__] = func
        return func  # normally a decorator returns a wrapped function, 
                     # but here we return func unmodified, after registering it
    registrar.all = registry
    return registrar

In [ ]:
reg = makeRegistrar()
@reg
def f1(a):
    return a+1

In [ ]:
def fN(n):
    return reg.all['f'+str(n)]

In [ ]:
fN(1)(2)

In [ ]:
def all_f():
    return reg.all
all_f()

OK now that's the basic principle, let's see if I can apply that to my problem...

In [ ]:
# My function needs to return a pandas Series and the registry needs to return a list of Series
from pandas import Series

def my_column():
    return Series(range(5, 10))

my_column()

In [ ]:
def export_as(new_name):
    registry = {}
    def registrar(func):
        registry[func.__name__] = new_name
        return func  # normally a decorator returns a wrapped function, 
                     # but here we return func unmodified, after registering it
    registrar.all = registry
    return registrar

In [ ]:
@export_as('hello')
def my_column():
    return Series(range(5, 10))

In [ ]:
export_as('hello').all

I looked for inspiration at Flask. Because somehow the route decorator does something close. Here it is:

In [ ]:
def route(rule, **options):
    def decorator(f):
        endpoint = options.pop('endpoint', None)
        self.add_url_rule(rule, endpoint, f, **options)
        return f
    return decorator

In [ ]:
def export_as(new_name):
    def decorator(f):
        setattr(f, 'is_exported', True)
        setattr(f, 'field', new_name)
        return f
    return decorator

In [ ]:
@export_as('hello')
def my_function():
    pass

In [ ]:
hasattr(my_function, 'is_exported')

In [ ]:
my_function.field

In [ ]:
dir()

In [ ]:
def needle_in_haystack(a):
    print(a)
    for item in a:
        if hasattr(getattr(item), 'is_exported'):
            print(getattr(item, 'field'))
needle_in_haystack(dir())

In [ ]:
globals()

In [1]:
uri.format(**db)
            conn = connect(uri)
            cur = conn.cursor()
            cur.execute(test)
            result = cur.fetchone()
            cur.close()
            conn.close()

NameError: name 'uri' is not defined

In [1]:
from pandas import DataFrame

In [2]:
df = DataFrame()

In [10]:
from datetime import datetime
odoo_df['timestamp'] = datetime.now()
odoo_df

,External ID,Active,Planday username,Backend UUID,Job Position,Salary ID,Driver App username,Name,Fleet/Name,timestamp
0,__export__.res_partner_2303,True,NaN,6f1596ed-cc2d-4f53-b2b1-405e830285b9,Driver,279198,aftabs,Aftab Shafqat,birmingham,2016-01-18 12:21:32.006602
1,__export__.res_partner_3010,True,NaN,86638e4b-8646-44f8-a4b7-ca1cb6d0d094,Valk Driver Leicester,284845,aaka,Aamir Karim,leicester,2016-01-18 12:21:32.006602
2,__export__.res_partner_1877,True,NaN,f14b717a-c873-4550-af43-61a590542502,Driver,274578,AaYa,Aamir Yaqoob,london_zone_20,2016-01-18 12:21:32.006602
3,__export__.res_partner_3749,True,NaN,NaN,Driver,NaN,Ajohnson,Aaron Johnson,manchester,2016-01-18 12:21:32.006602
4,__export__.res_partner_989,True,NaN,aa7d7e68-5b27-40b5-9e86-c5245fe8cc39,Driver,240035,apervaiz,Aasim Pervaiz,birmingham,2016-01-18 12:21:32.006602
5,__export__.res_partner_623,True,NaN,92a58abf-c431-41d1-a144-9724b8ad6e0b,Driver,227979,sabbas,"Abbas, Sam",nottingham,2016-01-18 12:21:32.006602
6,__export__.res_partner_3116,True,NaN,a42d1cf3-1c7a-4019-bf8d-217f4271065c,Driver,286568,azeboudj,Abdel Malek Zeboudj,london_zone_j,2016-01-18 12:21:32.006602
7,__export__.res_partner_1432,True,NaN,5e44a4b3-6abe-40ca-a08d-c15553fa7e88,Driver,268112,ahassan3,Abdihamid Hassan,NaN,2016-01-18 12:21:32.006602
8,__export__.res_partner_1143,True,NaN,5f922c71-9f5e-49b4-8af2-d121578bd833,Driver,259419,aahmed,Abdul Ahmed,birmingham,2016-01-18 12:21:32.006602
9,__export__.res_partner_1227,True,NaN,3c0036ff-5b3d-45fa-8400-f44de120f112,Driver,261550,abdulali,Abdul Aziz Ali,birmingham,2016-01-18 12:21:32.006602
10,__export__.res_partner_1712,True,NaN,981cc0d8-64a6-48bd-8069-894da2cb4f89,Driver,271980,abari,Abdul Bari,london_leyton_stratford,2016-01-18 12:21:32.006602
11,__export__.res_partner_1297,True,NaN,12762d6b-f7d4-49a5-89dd-c87c497f174e,Driver,264630,AKuddoos,Abdul Kuddoos,birmingham,2016-01-18 12:21:32.006602
12,__export__.res_partner_868,True,NaN,f3527488-d498-4a15-a86a-a54cd95dde88,Driver,250625,amukhtar,Abdul Mukhtar,birmingham,2016-01-18 12:21:32.006602
13,__export__.res_partner_3291,True,NaN,NaN,Driver,NaN,abmu,Abdul Mumum,manchester,2016-01-18 12:21:32.006602
14,__export__.res_partner_1498,True,NaN,NaN,Driver,NaN,aqkhan,Abdul Qadoos Khan,london_leyton_stratford,2016-01-18 12:21:32.006602
15,__export__.res_partner_2712,True,NaN,fcc60a64-364c-4b2a-9dd0-a4f3444d1ed6,Driver,281435,aqayum,Abdul Qayum,manchester,2016-01-18 12:21:32.006602
16,__export__.res_partner_2639,True,NaN,99e03930-8772-4b16-b80d-5f5e98bcd227,Valk Driver Leicester,280791,asattar,Abdul Sattar,leicester,2016-01-18 12:21:32.006602
17,__export__.res_partner_2848,True,NaN,b1153c3c-6c63-4cfd-92ec-373254a603e9,Driver,283192,ayasar,Abdul Yasar,manchester,2016-01-18 12:21:32.006602
18,__export__.res_partner_3201,True,NaN,NaN,Driver,NaN,rabdul,"Abdul, Rashid",derby,2016-01-18 12:21:32.006602
19,__export__.res_partner_1299,True,NaN,d4dc0e19-a2ec-4826-830b-d422e751a686,Driver,264636,AbSaleh,Abdulgafar Saleh,birmingham,2016-01-18 12:21:32.006602
20,__export__.res_partner_1416,True,NaN,NaN,Driver,NaN,aalnamer,Abdullah Alnamer,NaN,2016-01-18 12:21:32.006602
21,__export__.res_partner_1229,True,NaN,91bc01ed-9f52-44f7-adc4-71df445c60c4,Driver,261555,abdullahk,Abdullah Khan,birmingham,2016-01-18 12:21:32.006602
22,__export__.res_partner_3179,True,NaN,d4dc0e19-a2ec-4826-830b-d422e751a686,Driver,264636,absaleh,Abdulmalik Saleh,birmingham,2016-01-18 12:21:32.006602
23,__export__.res_partner_634,True,NaN,e7a071a0-130e-4248-8e88-c6c62c1c14c0,Driver,209395,wabdulrasheed,"Abdulrasheed, Waheed",nottingham,2016-01-18 12:21:32.006602
24,__export__.res_partner_1381,True,NaN,c44f7fd4-8bad-467e-8246-2273db8edf29,Driver,267481,aharvey,Abi Harvey,basildon,2016-01-18 12:21:32.006602
25,__export__.res_partner_2906,True,NaN,NaN,Driver,NaN,habid,"Abid, Hussain",derby,2016-01-18 12:21:32.006602
26,__export__.res_partner_616,True,NaN,4e17b81d-6633-456d-a5a7-e3b13eddaddf,Driver,197673,nabiolasalam,"Abiola Salam, Nurein",nottingham,2016-01-18 12:21:32.006602
27,__export__.res_partner_3362,True,NaN,NaN,NaN,NaN,adjoudi,Abouelkacem Djoudi,london_zone_b,2016-01-18 12:21:32.006602
28,__export__.res_partner_3453,True,NaN,NaN,driver,NaN,acmahmood,Aclack Mahmood,leeds,2016-01-18 12:21:32.006602
29,__export__.res_partner_2341,True,NaN,NaN,NaN,NaN,NaN,Adam Frynas,warszawa,2016-01-18 12:21:32.006602
...,...,...,...,...,...,...,...,...,...,...
874,__export__.res_partner_1713,True,NaN,d3c62c06-d648-4cbc-8b4a-41b302b3b01a,Driver,271299,wassiss,Wisley Cesar Assiss,NaN,2016-01-18 12:21:32.006602
875,__export__.res_partner_1192,True,NaN,285b5dcd-fb29-42f8-85f3-06c1c4ffb59c,Driver,261427,JWisniewski,"Wisniewski, Jakub",nottingham,2016-01-18 12:21:32.006602
876,__export__.res_partner_1652,True,NaN,NaN,Driver,NaN,awlodarczyk,"Wlodarczyk, Artur",NaN,2016-01-18 12:21:32.006602
877,__export__.res_partner_2186,True,NaN,3b643480-342f-4ad4-8c8d-e4772b470fa9,Driver,277912,yahchen,Yahya Chentouf,london_zone_a,2016-01-18 12:21:32.006602
878,__export__.res_partner_1411,True,NaN,b4c5ace4-12e1-4098-a0fe-300b8ba25e95,Driver,268095,ymohammed,Yahya Mohammed,NaN,2016-01-18 12:21:32.006602
879,__export__.res_partner_3258,True,NaN,e355ebfd-f3c5-425e-82a0-cd88dc8bd8f8,Driver,286791,yasali,Yasin Ali,birmingham,2016-01-18 12:21:32.006602
880,__export__.res_partner_1753,True,NaN,6ed2427d-2be8-4b37-9e5d-6cd1968def9a,Driver,272283,YMehmood,Yasir Mehmood,london_zone_g,2016-01-18 12:21:32.006602
881,__export__.res_partner_3016,True,NaN,1e7d3a9c-ac83-4e99-9fdd-530f035acd78,Driver,284974,ysiddi,Yasir Siddique,manchester,2016-01-18 12:21:32.006602
882,__export__.res_partner_1653,True,NaN,NaN,Driver,NaN,gyordanov,"Yordanov, Georgi",NaN,2016-01-18 12:21:32.006602
883,__export__.res_partner_3228,True,NaN,NaN,Driver,NaN,youalg,Yousef Alghergani,manchester,2016-01-18 12:21:32.006602
884,__export__.res_partner_2049,True,NaN,NaN,NaN,NaN,zrisva,Zafer Risvanoglu,berlin,2016-01-18 12:21:32.006602
885,__export__.res_partner_792,True,NaN,NaN,Driver,NaN,zhussain,Zafran Hussain,birmingham,2016-01-18 12:21:32.006602
886,__export__.res_partner_1265,True,NaN,d7cc126c-f6db-43de-bb64-73eeec675373,Driver,263447,zahussain,Zaid Hussain,basildon,2016-01-18 12:21:32.006602
887,__export__.res_partner_2659,True,NaN,7fb7d0cf-3924-4ce8-a98c-0272c840d474,NaN,283943,zmardiny,Zaid Mardiny,liverpool,2016-01-18 12:21:32.006602
888,__export__.res_partner_1703,True,NaN,a7978456-1c03-4e3a-8002-4074e1e92ac9,Driver,271014,zmujaba,Zain Mujtaba,london_zone_g,2016-01-18 12:21:32.006602
889,__export__.res_partner_1952,True,NaN,NaN,NaN,NaN,zakmah,Zak Mahmood Coventry,coventry,2016-01-18 12:21:32.006602
890,__export__.res_partner_3298,True,NaN,NaN,Driver,NaN,zlatif,Zakaria Latif,london_zone_f,2016-01-18 12:21:32.006602
891,__export__.res_partner_3135,True,NaN,NaN,Valk Driver,NaN,znaim,Zakaria Naim,northampton,2016-01-18 12:21:32.006602
892,__export__.res_partner_275,True,NaN,NaN,Driver,NaN,zmahmood,Zaki Mahmood,coventry,2016-01-18 12:21:32.006602
893,__export__.res_partner_1793,True,NaN,NaN,Driver,NaN,zshahid,"Zaman, Shahid",NaN,2016-01-18 12:21:32.006602
894,__export__.res_partner_3279,True,NaN,NaN,Driver,NaN,zezu,"Zeb, Zuhaib",london_zone_20,2016-01-18 12:21:32.006602
895,__export__.res_partner_1889,True,NaN,533db974-8865-43b2-ba08-e1e3a96d9c81,Driver,274586,zchadd,Zeeshan Chaddhar,london_leyton_stratford,2016-01-18 12:21:32.006602
896,__export__.res_partner_969,True,NaN,87020c74-b49a-48f2-b6a5-dc8e2d8cddfb,Driver,253779,ztoor,Zeeshan Toor,NaN,2016-01-18 12:21:32.006602
897,__export__.res_partner_2088,True,NaN,NaN,Driver,NaN,zack,Zein Ackrem,london_zone_a,2016-01-18 12:21:32.006602
898,__export__.res_partner_2096,True,NaN,d6cd83c9-382b-465f-bdd7-009743b16aaf,Driver,276854,ksaidul,karim Saidul,coventry,2016-01-18 12:21:32.006602
899,__export__.res_partner_3265,True,NaN,NaN,Driver,NaN,elineny,no one,london_zone_20,2016-01-18 12:21:32.006602
900,__export__.res_partner_3170,True,NaN,NaN,NaN,NaN,NaN,test 22,berlin,2016-01-18 12:21:32.006602
901,__export__.res_partner_1811,True,NaN,NaN,NaN,NaN,NaN,test driver,manchester,2016-01-18 12:21:32.006602
902,__export__.res_partner_2691,True,NaN,NaN,NaN,NaN,odinm,Özkan Dinmezkalp,berlin,2016-01-18 12:21:32.006602
903,__export__.res_partner_2350,True,NaN,NaN,NaN,NaN,NaN,Łukasz Rajchman,warszawa,2016-01-18 12:21:32.006602

In [ ]:
def write_to_excel():
    # DEFAULT_OUTPUT_DIR = join(expanduser('~'), 'sync_police')
    # excel_filepath = join(DEFAULT_OUTPUT_DIR, 'test.xlsx')
    # writer = ExcelWriter(excel_filepath)
    # planday_with_odoo.to_csv()
    # planday_with_odoo.to_excel(writer, 'planday with odoo')
    # backend_with_odoo.to_excel(writer, 'backend with odoo')
    # writer.save()